apiVersion: v2
name: bookstore
description: A simple CAP project.
type: application
version: 1.0.0-SNAPSHOT
appVersion: 1.0.0-SNAPSHOT
annotations:
  app.kubernetes.io/managed-by: cds-dk/helm
dependencies:
  - name: web-application
    alias: srv
    version: ">0.0.0"
  - name: web-application
    alias: approuter
    version: ">0.0.0"
  - name: service-instance
    alias: xsuaa
    version: ">0.0.0"
  - name: service-instance
    alias: hana
    version: ">0.0.0"
  - name: content-deployment
    alias: hana-deployer
    version: ">0.0.0"
image:
  repository: docker.io/bookstore-kyma/bookstore
  tag: latest

namespace: test
